### ISSUE TITLE
How to build and deploy to BTP CF

### ISSUE THREAD

**Issue by MartinPankraz** [Soontao/cds-mysql#14]
I am able to run your adapter in my dev environment on SAP BAS and actually see the data entries in my CAP service output. However, deploying is a challenge.

I am trying to derive the settings to build the solution and deploy to CF on SAP BTP from the mentioned PostgreSQL adapter, but with no luck so far. Find my project [here](https://github.com/MartinPankraz/private-sql-glory-sap-btp).

Could you add a section or give me some pointers on how to deploy the project including the mysql adapter?

KR
Martin

**Comment by Soontao** [comment]
Hi @MartinPankraz 

Sorry, i'm on vacation now, maybe I'll update the reply after January, 4.

Just double confirm with you, you need a document/example

* deployed to SAP BTP
* connect to Azure with private link service
* with mta config
* deploy db 
* run service

is that enough. 

Regards,
Theo

**Comment by MartinPankraz** [comment]
Hey Theo,

deploy to BTP with either mta or cf config would be enough.

Private Link I am covering as with my other prototypes. No need to input there, except you want to join the [conversation](https://blogs.sap.com/2021/12/29/getting-started-with-btp-private-link-service-for-azure/) on the SAP community :-)

Deploy Mariadb or MySQL would be a challenge, because it would not be done with BTP native means. MySQL or Maria need to be deployed using CLI, ARM templates or any other supported Microsoft interface.

KR
Martin

**Comment by Soontao** [comment]
Hi @MartinPankraz 

just go to [this repo](https://github.com/Soontao/odata-v4-cap-demo#by-default-envjson-local-development-only) to get an example with deployment, I just provided the very basic sample which minimal could be used. 


```yml
## Generated mta.yaml based on template version 0.4.0
## appName = cap-demo
## language=nodejs; multitenant=false
_schema-version: "3.1"
ID: cap-demo
version: 1.0.0
description: "cap-demo"
parameters:
  enable-parallel-deployments: true

build-parameters:
  before-all:
    - builder: custom
      commands:
        - npm install
        - npx -p @sap/cds-dk cds build --production

modules:
  # --------------------- SERVER MODULE ------------------------
  - name: cap-demo-srv
    # ------------------------------------------------------------
    type: nodejs
    path: gen/srv
    parameters:
      buildpack: nodejs_buildpack
      tasks:
        - name: deploy db
          command: npm run deploy
    requires:
      - name: remote-mysql-service # change this name if the user-provided service has another key

resources:
  - name: remote-mysql-service
    type: org.cloudfoundry.user-provided-service

```

I also have some other question about private link, does  the private link service could create service instance on  cloud foundry, could it create service key/service binding? and what the `tags` of the instances bindings

I'll review your document firstly, this comment just be a quick update for this issue. 

Regards,
Theo
